/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionecamposportivoasvalle.tta;

import java.io.Serializable;

/**
 *
 * @author valletta.enrico
 */
public class Calcio extends javax.swing.JFrame implements Serializable{
    public String Sport;
    /**
     * Creates new form Calcio
     */
    public Calcio() {
        initComponents();
        setResizable(false);
    }
    public Calcio(String Sport) {
        this.Sport=Sport;
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbn_Calcio5 = new javax.swing.JButton();
        jbn_Calcio8 = new javax.swing.JButton();
        jbn_Indietro = new javax.swing.JButton();
        jbn_Calcio11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(478, 442));
        jPanel1.setMinimumSize(new java.awt.Dimension(478, 442));
        jPanel1.setLayout(null);

        jbn_Calcio5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jbn_Calcio5.setText("CALCIO A 5");
        jbn_Calcio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_Calcio5ActionPerformed(evt);
            }
        });
        jPanel1.add(jbn_Calcio5);
        jbn_Calcio5.setBounds(40, 180, 150, 49);

        jbn_Calcio8.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jbn_Calcio8.setText("CALCIO A 8");
        jbn_Calcio8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_Calcio8ActionPerformed(evt);
            }
        });
        jPanel1.add(jbn_Calcio8);
        jbn_Calcio8.setBounds(288, 180, 150, 49);

        jbn_Indietro.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jbn_Indietro.setText("INDIETRO");
        jbn_Indietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_IndietroActionPerformed(evt);
            }
        });
        jPanel1.add(jbn_Indietro);
        jbn_Indietro.setBounds(170, 350, 140, 54);

        jbn_Calcio11.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jbn_Calcio11.setText("CALCIO A 11");
        jbn_Calcio11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_Calcio11ActionPerformed(evt);
            }
        });
        jPanel1.add(jbn_Calcio11);
        jbn_Calcio11.setBounds(160, 260, 150, 54);

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecamposportivoasvalle/tta/Soccer_Ball_icon-icons.com_76265.png"))); // NOI18N
        jLabel1.setText("CALCIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(170, 100, 140, 64);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecamposportivoasvalle/tta/fotor-ai-2024022294942 (Personalizzato).jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 460, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_IndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_IndietroActionPerformed
        // TODO add your handling code here:
        Menù a=new Menù();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbn_IndietroActionPerformed

    private void jbn_Calcio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_Calcio5ActionPerformed
        // TODO add your handling code here:
        String Tipo="Calcio a 5";
        PrenotazioneCampo a=new PrenotazioneCampo(Sport,Tipo);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbn_Calcio5ActionPerformed

    private void jbn_Calcio8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_Calcio8ActionPerformed
        // TODO add your handling code here:
        String Tipo="Calcio a 8";
        PrenotazioneCampo a=new PrenotazioneCampo(Sport,Tipo);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbn_Calcio8ActionPerformed

    private void jbn_Calcio11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_Calcio11ActionPerformed
        // TODO add your handling code here:
        String Tipo="Calcio a 11";
        PrenotazioneCampo a=new PrenotazioneCampo(Sport,Tipo);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbn_Calcio11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbn_Calcio11;
    private javax.swing.JButton jbn_Calcio5;
    private javax.swing.JButton jbn_Calcio8;
    private javax.swing.JButton jbn_Indietro;
    // End of variables declaration//GEN-END:variables
}
