/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionecamposportivoasvalle.tta;

import java.io.*;
import java.util.*;
import java.awt.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author micro
 */
public class Menù extends javax.swing.JFrame implements Serializable{
    private static final ArrayList prenotazioni= new ArrayList(1);
    //private prenotazioni p= new prenotazioni();
    /**
     * Creates new form Menù
     */
    public Menù() {
        initComponents();
        setResizable(false);
        ControllaFile();
    }
    
    /*public Menù() {
        initComponents();
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PCS = new javax.swing.JLabel();
        jbn_Esci = new javax.swing.JButton();
        jbn_Prenota = new javax.swing.JButton();
        jbn_Admin = new javax.swing.JButton();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRENOTAZIONE CAMPI SPORTIVI Sponsored By AS Valle(tta) - Produced by ngelo Chiriacopulos ");
        setMinimumSize(new java.awt.Dimension(1200, 545));
        getContentPane().setLayout(null);

        PCS.setBackground(new java.awt.Color(0, 0, 0));
        PCS.setFont(new java.awt.Font("Segoe UI Variable", 1, 48)); // NOI18N
        PCS.setForeground(new java.awt.Color(255, 255, 255));
        PCS.setText("PRENOTAZIONE CAMPI SPORTIVI");
        getContentPane().add(PCS);
        PCS.setBounds(230, 90, 800, 160);

        jbn_Esci.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jbn_Esci.setText("ESCI");
        jbn_Esci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_EsciActionPerformed(evt);
            }
        });
        getContentPane().add(jbn_Esci);
        jbn_Esci.setBounds(570, 360, 80, 50);

        jbn_Prenota.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jbn_Prenota.setText("PRENOTA");
        jbn_Prenota.setToolTipText("");
        jbn_Prenota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_PrenotaActionPerformed(evt);
            }
        });
        getContentPane().add(jbn_Prenota);
        jbn_Prenota.setBounds(560, 290, 100, 60);

        jbn_Admin.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jbn_Admin.setText("ADMIN");
        jbn_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_AdminActionPerformed(evt);
            }
        });
        getContentPane().add(jbn_Admin);
        jbn_Admin.setBounds(20, 30, 72, 23);

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecamposportivoasvalle/tta/SfondoMenu.jpg"))); // NOI18N
        getContentPane().add(sfondo);
        sfondo.setBounds(0, 10, 1240, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_EsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_EsciActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbn_EsciActionPerformed

    private void jbn_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_AdminActionPerformed
        // TODO add your handling code here:
        PasswordAdmin a= new PasswordAdmin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbn_AdminActionPerformed

    private void jbn_PrenotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_PrenotaActionPerformed

        Object[] options = {"Calcio", "Tennis", "Basket"};
        int choice = JOptionPane.showOptionDialog(
                null,                    
                "Scegli un'opzione:",    
                "Scelta",    
                JOptionPane.DEFAULT_OPTION,  
                JOptionPane.QUESTION_MESSAGE, 
                null,                    
                options,                 
                options[0]);
        if (choice==0){
            String Sport="Calcio";
            Calcio a=new Calcio(Sport);
            a.setVisible(true);
            this.dispose();
        }
        if (choice==1){
            String Sport="Tennis";
            Tennis a=new Tennis(Sport);
            a.setVisible(true);
            this.dispose();
        }
        if (choice==2){
            String Sport="Basket";
            Basket a=new Basket(Sport);
            a.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jbn_PrenotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menù.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menù.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menù.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menù.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menù().setVisible(true);
            }
        });
    }

    private static boolean ControllaFile() {
        boolean caricato = false;
        File f = new File("prenotazioni.dat");
        if (f.exists()) {
            caricato = true;
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Il file PRENOTAZIONI.DAT è stato eliminato prima dell'esecuzione", "Attenzione", JOptionPane.WARNING_MESSAGE);
        }
        return caricato;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PCS;
    private javax.swing.JButton jbn_Admin;
    private javax.swing.JButton jbn_Esci;
    private javax.swing.JButton jbn_Prenota;
    private javax.swing.JLabel sfondo;
    // End of variables declaration//GEN-END:variables
}
