/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionecamposportivoasvalle.tta;

/**
 *
 * @author valletta.enrico
 */
public class Tennis extends javax.swing.JFrame {
    public String Sport;
    /**
     * Creates new form Tennis
     */
    public Tennis() {
        initComponents();
        setResizable(false);
    }
    public Tennis(String Sport) {
        this.Sport=Sport;
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbn_TennisSingolo = new javax.swing.JButton();
        jbn_TennisCoppie = new javax.swing.JButton();
        jbn_Indietro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(526, 411));
        setMinimumSize(new java.awt.Dimension(526, 411));
        getContentPane().setLayout(null);

        jbn_TennisSingolo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbn_TennisSingolo.setText("SINGOLO");
        jbn_TennisSingolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_TennisSingoloActionPerformed(evt);
            }
        });
        getContentPane().add(jbn_TennisSingolo);
        jbn_TennisSingolo.setBounds(64, 171, 110, 50);

        jbn_TennisCoppie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbn_TennisCoppie.setText("COPPIE");
        jbn_TennisCoppie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_TennisCoppieActionPerformed(evt);
            }
        });
        getContentPane().add(jbn_TennisCoppie);
        jbn_TennisCoppie.setBounds(335, 171, 102, 50);

        jbn_Indietro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbn_Indietro.setText("INDIETRO");
        jbn_Indietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_IndietroActionPerformed(evt);
            }
        });
        getContentPane().add(jbn_Indietro);
        jbn_Indietro.setBounds(220, 330, 100, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecamposportivoasvalle/tta/5023365.png"))); // NOI18N
        jLabel2.setText("TENNIS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 50, 140, 50);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 20, 140, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecamposportivoasvalle/tta/jannicsinner.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-60, 0, 640, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_TennisSingoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_TennisSingoloActionPerformed
        // TODO add your handling code here:
        String Tipo="Singolo";
        PrenotazioneCampo a=new PrenotazioneCampo(Sport,Tipo);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbn_TennisSingoloActionPerformed

    private void jbn_TennisCoppieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_TennisCoppieActionPerformed
        // TODO add your handling code here:
        String Tipo="Coppie";
        PrenotazioneCampo a=new PrenotazioneCampo(Sport,Tipo);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbn_TennisCoppieActionPerformed

    private void jbn_IndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_IndietroActionPerformed
        // TODO add your handling code here:
        Menù a=new Menù();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbn_IndietroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tennis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tennis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tennis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tennis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tennis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbn_Indietro;
    private javax.swing.JButton jbn_TennisCoppie;
    private javax.swing.JButton jbn_TennisSingolo;
    // End of variables declaration//GEN-END:variables
}
